[
  {
    "project": "models",
    "commit": "d3610769",
    "parent_commit": "d62ddcaa8f6cb6809acf89e549109079d8c010c6",
    "warning_removed": 1,
    "parent_warnings": [
      [
        "official/resnet/keras/keras_benchmark.py:30:21 Undefined or invalid type [11]: Annotation `tf.test.Benchmark` is not defined as a type."
      ]
    ],
    "warnings": []
  },
  {
    "project": "models",
    "commit": "c24e1f41",
    "parent_commit": "eb7c6e43ffbe2e45b2a8620cd178f33ed7a9ea4d",
    "warning_removed": 3,
    "parent_warnings": [
      [
        "research/neural_gpu/neural_gpu.py:1:1 Parsing failure [404]: Could not parse file at research/neural_gpu/neural_gpu.py:503:79-503:79"
      ],
      [
        "research/neural_gpu/program_utils.py:1:1 Parsing failure [404]: Could not parse file at research/neural_gpu/program_utils.py:180:19-180:19"
      ],
      [
        "research/neural_programmer/neural_programmer.py:1:1 Parsing failure [404]: Could not parse file at research/neural_programmer/neural_programmer.py:187:8-187:8"
      ]
    ],
    "warnings": []
  },
  {
    "project": "models",
    "commit": "2c181308",
    "parent_commit": "caafb6d119088d29e57779a66e949056dc116efb",
    "warning_removed": 26,
    "parent_warnings": [
      [
        "research/astronet/astronet/astro_cnn_model/astro_cnn_model.py:54:20 Undefined or invalid type [11]: Annotation `astro_model.AstroModel` is not defined as a type."
      ],
      [
        "research/astronet/astronet/astro_cnn_model/astro_cnn_model_test.py:31:24 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astronet/astro_fc_model/astro_fc_model.py:58:19 Undefined or invalid type [11]: Annotation `astro_model.AstroModel` is not defined as a type."
      ],
      [
        "research/astronet/astronet/astro_fc_model/astro_fc_model_test.py:31:23 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astronet/astro_model/astro_model_test.py:31:21 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astronet/ops/dataset_ops_test.py:37:21 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astronet/ops/input_ops_test.py:27:19 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astronet/ops/metrics_test.py:52:18 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astrowavenet/astrowavenet_model_test.py:28:23 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astrowavenet/data/base_test.py:36:22 Undefined or invalid type [11]: Annotation `base.TFRecordDataset` is not defined as a type.",
        "research/astronet/astrowavenet/data/base_test.py:98:26 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astrowavenet/data/kepler_light_curves.py:29:24 Undefined or invalid type [11]: Annotation `base.TFRecordDataset` is not defined as a type."
      ],
      [
        "research/astronet/astrowavenet/data/synthetic_transit_maker_test.py:27:32 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/astrowavenet/data/synthetic_transits.py:37:24 Undefined or invalid type [11]: Annotation `base.DatasetBuilder` is not defined as a type."
      ],
      [
        "research/astronet/light_curve/fast_ops/python/median_filter_test.py:27:23 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/light_curve/fast_ops/python/phase_fold_test.py:27:24 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/light_curve/fast_ops/python/view_generator_test.py:27:24 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/light_curve/kepler_io_test.py:34:19 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/light_curve/median_filter_test.py:27:23 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/light_curve/periodic_event_test.py:26:16 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/light_curve/util_test.py:29:25 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/tf_util/config_util_test.py:26:21 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/tf_util/configdict_test.py:26:21 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/tf_util/example_util_test.py:27:22 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/third_party/kepler_spline/kepler_spline_test.py:13:23 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ],
      [
        "research/astronet/third_party/robust_mean/robust_mean_test.py:14:21 Undefined or invalid type [11]: Annotation `absltest.TestCase` is not defined as a type."
      ]
    ],
    "warnings": []
  }
]