[
  {
    "project": "keras",
    "commit": "967817c2",
    "parent_commit": "d42537dff5a7fb288f3de7aef79e7a72b6d44a8d",
    "warning_removed": 2,
    "parent_warnings": [
      [
        "keras/engine/base_preprocessing_layer.py:24:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/engine/base_preprocessing_layer.py:25:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.compat.v2`.",
        "keras/engine/base_preprocessing_layer.py:27:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.python.eager`.",
        "keras/engine/base_preprocessing_layer.py:28:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.python.util.tf_export`.",
        "keras/engine/base_preprocessing_layer.py:29:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.tools.docs`."
      ],
      [
        "keras/engine/base_preprocessing_layer_test.py:18:0 Undefined import [21]: Could not find a module corresponding to import `absl.testing`.",
        "keras/engine/base_preprocessing_layer_test.py:25:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/engine/base_preprocessing_layer_test.py:26:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.compat.v2`."
      ]
    ],
    "warnings": [
      [
        "keras/engine/base_preprocessing_layer.py:22:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.compat.v2`.",
        "keras/engine/base_preprocessing_layer.py:24:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.python.eager`.",
        "keras/engine/base_preprocessing_layer.py:25:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.python.util.tf_export`.",
        "keras/engine/base_preprocessing_layer.py:26:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.tools.docs`."
      ],
      [
        "keras/engine/base_preprocessing_layer_test.py:23:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/engine/base_preprocessing_layer_test.py:24:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.compat.v2`."
      ]
    ]
  },
  {
    "project": "keras",
    "commit": "5040aa38",
    "parent_commit": "cb8f0a83e68efbe10c9d54a15d234dae8a594375",
    "warning_removed": 1,
    "parent_warnings": [
      [
        "keras/datasets/imdb.py:2:0 Undefined import [21]: Could not find a module corresponding to import `cPickle`.",
        "keras/datasets/imdb.py:7:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ],
    "warnings": [
      [
        "keras/datasets/imdb.py:7:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ]
  },
  {
    "project": "keras",
    "commit": "d8446ef6",
    "parent_commit": "2bc43bff1e243f4031690277b67f60592c1edf58",
    "warning_removed": 1,
    "parent_warnings": [
      [
        "examples/cifar10_cnn_tfaugment2d.py:52:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow`."
      ]
    ],
    "warnings": []
  },
  {
    "project": "keras",
    "commit": "36eff96a",
    "parent_commit": "e7859bf1884bb1455451e95d579a0db00f0fbfbd 829dff1866e71c3afa992054212ec66a8d467cfc",
    "warning_removed": 14,
    "parent_warnings": [
      [
        "keras/datasets/reuters.py:7:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/datasets/reuters.py:72:4 Unbound name [10]: Name `make_reuters_dataset` is used but not defined in the current scope."
      ],
      [
        "tests/keras/datasets/test_datasets.py:2:0 Undefined import [21]: Could not find a module corresponding to import `pytest`."
      ],
      [
        "tests/keras/layers/test_advanced_activations.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/layers/test_advanced_activations.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`.",
        "tests/keras/layers/test_advanced_activations.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/layers/test_call.py:3:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/layers/test_call.py:4:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_call.py:5:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/layers/test_convolutional.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/layers/test_convolutional.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_convolutional.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/layers/test_core.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/layers/test_core.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_core.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/layers/test_embeddings.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/layers/test_embeddings.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_embeddings.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/layers/test_recurrent.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/layers/test_recurrent.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_recurrent.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/preprocessing/test_image.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/preprocessing/test_image.py:4:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/test_activations.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_activations.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_activations.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/test_constraints.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_constraints.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_constraints.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/test_models.py:3:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_models.py:4:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/test_normalization.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_normalization.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_normalization.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/test_optimizers.py:2:0 Undefined import [21]: Could not find a module corresponding to import `pytest`."
      ],
      [
        "tests/keras/test_regularizers.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_regularizers.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/wrappers/test_scikit_learn.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/wrappers/test_scikit_learn.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ],
    "warnings": [
      [
        "keras/datasets/reuters.py:10:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/layers/test_call.py:7:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_call.py:9:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/layers/test_convolutional.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_convolutional.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/layers/test_core.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_core.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/layers/test_recurrent.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/test_activations.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_activations.py:4:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/test_constraints.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_constraints.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/test_normalization.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_normalization.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ]
    ]
  },
  {
    "project": "keras",
    "commit": "7552f2c2",
    "parent_commit": "55d9374961d9d0f62241dbd4db0920981dd1dfc8 0eea5f8867bb2ef68c116e7c827436f59ef11a2e",
    "warning_removed": 6,
    "parent_warnings": [
      [
        "tests/keras/layers/test_wrappers.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/layers/test_wrappers.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/layers/test_wrappers.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`."
      ],
      [
        "tests/keras/preprocessing/test_image.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/preprocessing/test_image.py:4:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/test_graph_model.py:3:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_graph_model.py:5:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/test_sequential_model.py:3:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_sequential_model.py:5:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ],
    "warnings": []
  },
  {
    "project": "keras",
    "commit": "7ccfb370",
    "parent_commit": "10b165f06ec9385ed7251b46eef22836bd04ad55 71ec611117d1bcbe8f49bc432200aa041bffefcb",
    "warning_removed": 3,
    "parent_warnings": [
      [
        "keras/utils/traceback_utils.py:22:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.compat.v2`."
      ],
      [
        "keras/utils/traceback_utils_test.py:19:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.compat.v2`.",
        "keras/utils/traceback_utils_test.py:22:25 Undefined or invalid type [11]: Annotation `tf.test.TestCase` is not defined as a type."
      ]
    ],
    "warnings": []
  },
  {
    "project": "keras",
    "commit": "93b7dd99",
    "parent_commit": "9256b7622698e8728a7c8a035854f96ebaee14c4",
    "warning_removed": 1,
    "parent_warnings": [
      [
        "tests/keras/test_callbacks.py:5:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_callbacks.py:6:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/test_callbacks.py:193:4 Undefined import [21]: Could not find a module corresponding to import `tensorflow`."
      ]
    ],
    "warnings": [
      [
        "tests/keras/test_callbacks.py:5:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_callbacks.py:6:0 Undefined import [21]: Could not find a module corresponding to import `pytest`."
      ]
    ]
  },
  {
    "project": "keras",
    "commit": "aa826d68",
    "parent_commit": "84711475f8db72ac573a2584cb85f8d6ff5facef",
    "warning_removed": 3,
    "parent_warnings": [
      [
        "examples/imdb_cnn.py:10:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "examples/imdb_cnn_lstm.py:7:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "examples/imdb_lstm.py:14:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ],
    "warnings": []
  },
  {
    "project": "keras",
    "commit": "9b0ff98e",
    "parent_commit": "27e943eda20b939087329bd032219c9b85d39d43 c8282437a7f75f9c3af7a1b2ad57297be41863ff",
    "warning_removed": 13,
    "parent_warnings": [
      [
        "examples/conv_filter_visualization.py:8:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/conv_filter_visualization.py:9:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "examples/conv_filter_visualization.py:71:15 Undefined attribute [16]: Module `keras.backend` has no attribute `mean`.",
        "examples/conv_filter_visualization.py:73:15 Undefined attribute [16]: Module `keras.backend` has no attribute `mean`.",
        "examples/conv_filter_visualization.py:76:12 Undefined attribute [16]: Module `keras.backend` has no attribute `gradients`.",
        "examples/conv_filter_visualization.py:82:14 Undefined attribute [16]: Module `keras.backend` has no attribute `function`."
      ],
      [
        "examples/deep_dream.py:1:1 Analysis failure [30]: Pyre gave up inferring types for some variables because function `examples.deep_dream.$toplevel` was too complex.",
        "examples/deep_dream.py:19:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "examples/deep_dream.py:20:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/deep_dream.py:21:0 Undefined import [21]: Could not find a module corresponding to import `scipy.optimize`.",
        "examples/deep_dream.py:123:7 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/deep_dream.py:132:24 Undefined attribute [16]: Module `keras.backend` has no attribute `sum`.",
        "examples/deep_dream.py:132:30 Undefined attribute [16]: Module `keras.backend` has no attribute `square`.",
        "examples/deep_dream.py:134:24 Undefined attribute [16]: Module `keras.backend` has no attribute `sum`.",
        "examples/deep_dream.py:134:30 Undefined attribute [16]: Module `keras.backend` has no attribute `square`.",
        "examples/deep_dream.py:139:31 Undefined attribute [16]: Module `keras.backend` has no attribute `sum`.",
        "examples/deep_dream.py:139:37 Undefined attribute [16]: Module `keras.backend` has no attribute `square`.",
        "examples/deep_dream.py:144:8 Undefined attribute [16]: Module `keras.backend` has no attribute `gradients`.",
        "examples/deep_dream.py:152:12 Undefined attribute [16]: Module `keras.backend` has no attribute `function`."
      ],
      [
        "examples/neural_doodle.py:45:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "examples/neural_doodle.py:46:0 Undefined import [21]: Could not find a module corresponding to import `scipy.optimize`.",
        "examples/neural_doodle.py:47:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/neural_doodle.py:124:8 Undefined import [21]: Could not find a module corresponding to import `sklearn.cluster`.",
        "examples/neural_doodle.py:127:8 Undefined import [21]: Could not find a module corresponding to import `scipy.cluster.vq`.",
        "examples/neural_doodle.py:171:14 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_doodle.py:172:15 Undefined attribute [16]: Module `keras.backend` has no attribute `placeholder`.",
        "examples/neural_doodle.py:174:20 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_doodle.py:176:20 Undefined attribute [16]: Module `keras.backend` has no attribute `zeros`.",
        "examples/neural_doodle.py:178:9 Undefined attribute [16]: Module `keras.backend` has no attribute `concatenate`.",
        "examples/neural_doodle.py:182:13 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_doodle.py:183:14 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_doodle.py:184:8 Undefined attribute [16]: Module `keras.backend` has no attribute `concatenate`.",
        "examples/neural_doodle.py:285:7 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_doodle.py:300:13 Undefined attribute [16]: Module `keras.backend` has no attribute `gradients`.",
        "examples/neural_doodle.py:309:12 Undefined attribute [16]: Module `keras.backend` has no attribute `function`."
      ],
      [
        "examples/neural_style_transfer.py:54:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/neural_style_transfer.py:55:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "examples/neural_style_transfer.py:56:0 Undefined import [21]: Could not find a module corresponding to import `scipy.optimize`.",
        "examples/neural_style_transfer.py:124:13 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_style_transfer.py:125:24 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_style_transfer.py:129:24 Undefined attribute [16]: Module `keras.backend` has no attribute `placeholder`.",
        "examples/neural_style_transfer.py:131:24 Undefined attribute [16]: Module `keras.backend` has no attribute `placeholder`.",
        "examples/neural_style_transfer.py:134:15 Undefined attribute [16]: Module `keras.backend` has no attribute `concatenate`.",
        "examples/neural_style_transfer.py:201:7 Undefined attribute [16]: Module `keras.backend` has no attribute `variable`.",
        "examples/neural_style_transfer.py:220:8 Undefined attribute [16]: Module `keras.backend` has no attribute `gradients`.",
        "examples/neural_style_transfer.py:228:12 Undefined attribute [16]: Module `keras.backend` has no attribute `function`."
      ],
      [
        "keras/backend/common.py:1:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "keras/backend/tensorflow_backend.py:1:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow`.",
        "keras/backend/tensorflow_backend.py:2:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.python.training`.",
        "keras/backend/tensorflow_backend.py:3:0 Undefined import [21]: Could not find a module corresponding to import `tensorflow.python.ops`.",
        "keras/backend/tensorflow_backend.py:9:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "keras/backend/theano_backend.py:3:0 Undefined import [21]: Could not find a module corresponding to import `theano`.",
        "keras/backend/theano_backend.py:5:0 Undefined import [21]: Could not find a module corresponding to import `theano.sandbox.rng_mrg`.",
        "keras/backend/theano_backend.py:6:0 Undefined import [21]: Could not find a module corresponding to import `theano.tensor.signal`.",
        "keras/backend/theano_backend.py:7:0 Undefined import [21]: Could not find a module corresponding to import `theano.printing`.",
        "keras/backend/theano_backend.py:9:4 Undefined import [21]: Could not find a module corresponding to import `theano.sparse`.",
        "keras/backend/theano_backend.py:13:4 Undefined import [21]: Could not find a module corresponding to import `theano.tensor.nnet.nnet`.",
        "keras/backend/theano_backend.py:15:4 Undefined import [21]: Could not find a module corresponding to import `theano.sandbox.softsign`.",
        "keras/backend/theano_backend.py:17:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "keras/utils/vis_utils.py:6:4 Undefined import [21]: Could not find a module corresponding to import `pydot_ng`.",
        "keras/utils/vis_utils.py:10:8 Undefined import [21]: Could not find a module corresponding to import `pydot`."
      ],
      [
        "tests/keras/backend/backend_test.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/backend/backend_test.py:2:0 Undefined import [21]: Could not find a module corresponding to import `numpy.testing`.",
        "tests/keras/backend/backend_test.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/backend/backend_test.py:4:0 Undefined import [21]: Could not find a module corresponding to import `scipy.sparse`."
      ],
      [
        "tests/keras/legacy/interface_test.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`."
      ],
      [
        "tests/keras/legacy/layers_test.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/legacy/layers_test.py:11:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "tests/keras/legacy/models_test.py:3:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.",
        "tests/keras/legacy/models_test.py:5:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ],
    "warnings": [
      [
        "examples/conv_filter_visualization.py:8:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/conv_filter_visualization.py:9:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ],
      [
        "examples/deep_dream.py:1:1 Analysis failure [30]: Pyre gave up inferring types for some variables because function `examples.deep_dream.$toplevel` was too complex.",
        "examples/deep_dream.py:19:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "examples/deep_dream.py:20:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/deep_dream.py:21:0 Undefined import [21]: Could not find a module corresponding to import `scipy.optimize`."
      ],
      [
        "examples/neural_doodle.py:45:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "examples/neural_doodle.py:46:0 Undefined import [21]: Could not find a module corresponding to import `scipy.optimize`.",
        "examples/neural_doodle.py:47:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/neural_doodle.py:124:8 Undefined import [21]: Could not find a module corresponding to import `sklearn.cluster`.",
        "examples/neural_doodle.py:127:8 Undefined import [21]: Could not find a module corresponding to import `scipy.cluster.vq`."
      ],
      [
        "examples/neural_style_transfer.py:54:0 Undefined import [21]: Could not find a module corresponding to import `scipy.misc`.",
        "examples/neural_style_transfer.py:55:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "examples/neural_style_transfer.py:56:0 Undefined import [21]: Could not find a module corresponding to import `scipy.optimize`."
      ]
    ]
  },
  {
    "project": "keras",
    "commit": "217cdd8b",
    "parent_commit": "65b5899d068daadb9101025dd8b8a7e4ceecec35",
    "warning_removed": 1,
    "parent_warnings": [
      [
        "tests/keras/test_objectives.py:1:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "tests/keras/test_objectives.py:7:41 Undefined attribute [16]: Module `keras.objectives` has no attribute `root_mean_squared_error`."
      ]
    ],
    "warnings": [
      [
        "tests/keras/test_objectives.py:1:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ]
  },
  {
    "project": "keras",
    "commit": "a744b600",
    "parent_commit": "52dac5e4b3e0e3a913f8c709ea4983f52f11d6d7",
    "warning_removed": 4,
    "parent_warnings": [
      [
        "keras/layers/containers.py:6:0 Undefined import [21]: Could not find a module corresponding to import `theano.tensor`."
      ],
      [
        "keras/layers/core.py:5:0 Undefined import [21]: Could not find a module corresponding to import `theano`.",
        "keras/layers/core.py:6:0 Undefined import [21]: Could not find a module corresponding to import `theano.tensor`.",
        "keras/layers/core.py:7:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/layers/core.py:17:0 Undefined import [21]: Could not find a module corresponding to import `theano.sandbox.rng_mrg`."
      ],
      [
        "keras/layers/normalization.py:5:0 Undefined import [21]: Could not find a module corresponding to import `theano.tensor`."
      ],
      [
        "keras/utils/layer_utils.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/utils/layer_utils.py:4:0 Undefined import [21]: Could not find a module corresponding to import `theano`.",
        "keras/utils/layer_utils.py:11:0 Undefined import [21]: Could not find a name `WordContextProduct` defined in module `keras.layers.embeddings`."
      ]
    ],
    "warnings": [
      [
        "keras/layers/core.py:5:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/layers/core.py:409:12 Undefined import [21]: Could not find a module corresponding to import `theano`."
      ],
      [
        "keras/utils/layer_utils.py:3:0 Undefined import [21]: Could not find a module corresponding to import `numpy`."
      ]
    ]
  },
  {
    "project": "keras",
    "commit": "25ed701d",
    "parent_commit": "875c5214137401f2e29ed7995940d8cb6613a350 7b8363632ee6787f05dc68864d29807bd60e0e24",
    "warning_removed": 2,
    "parent_warnings": [
      [
        "keras/applications/audio_conv_utils.py:1:0 Undefined import [21]: Could not find a module corresponding to import `numpy`.",
        "keras/applications/audio_conv_utils.py:35:8 Undefined import [21]: Could not find a module corresponding to import `librosa`."
      ]
    ],
    "warnings": []
  }
]